export {default as Login} from './Login/Login'
export {default as Register} from './Register/Register'
export {default as Home} from './Home/Home'
export {default as Users} from './Users/Users'
export {default as Warning} from './Warning/Warning'